//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEH {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    public sealed partial class APIInfoSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static APIInfoSettings defaultInstance = ((APIInfoSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new APIInfoSettings())));
        
        public static APIInfoSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KeywordSearchNaverCustomerID {
            get {
                return ((string)(this["KeywordSearchNaverCustomerID"]));
            }
            set {
                this["KeywordSearchNaverCustomerID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KeywordSearchNaverApiKey {
            get {
                return ((string)(this["KeywordSearchNaverApiKey"]));
            }
            set {
                this["KeywordSearchNaverApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KeywordSearchNaverSecret {
            get {
                return ((string)(this["KeywordSearchNaverSecret"]));
            }
            set {
                this["KeywordSearchNaverSecret"] = value;
            }
        }
    }
}
